### ISSUE TITLE
[ISSUE] Can't Run the image

### ISSUE THREAD

**Issue by Techks** [SpEcHiDe/PublicLeech#132]
Hello I'm New to this 
i Created Image using docker and then ran the image and i get this error 

enter APP_ID's value: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/app/tobrot/__init__.py", line 20, in <module>
    from tobrot.sample_config import Config
  File "/app/tobrot/sample_config.py", line 19, in <module>
    class Config:
  File "/app/tobrot/sample_config.py", line 23, in Config
    APP_ID = int(get_config("APP_ID", should_prompt=True))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

help me to fix this
![error](https://user-images.githubusercontent.com/37665945/95773240-b80a8380-0cdb-11eb-9108-0e818f45243b.JPG)

**Comment by SpEcHiDe** [comment]
enter values, when prompted? 🤔😬

**Comment by Techks** [comment]
can't enter values 
error code comes after running the image
